-- Jalankan di Supabase SQL Editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  role text not null check (role in ('kasir', 'direktur', 'admin')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.incomes (
  id bigint generated by default as identity primary key,
  date date not null,
  amount numeric(14,2) not null check (amount > 0),
  description text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  date date not null,
  category text not null check (category in ('PT BMKP', 'PT BMKU')),
  amount numeric(14,2) not null check (amount > 0),
  description text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_by uuid references auth.users(id),
  approved_by uuid references auth.users(id),
  approval_note text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.incomes enable row level security;
alter table public.expenses enable row level security;

create policy "authenticated users can read profiles" on public.profiles for select to authenticated using (true);
create policy "authenticated users can read incomes" on public.incomes for select to authenticated using (true);
create policy "cashier can create incomes" on public.incomes for insert to authenticated with check (true);
create policy "authenticated users can read expenses" on public.expenses for select to authenticated using (true);
create policy "authenticated users can create expenses" on public.expenses for insert to authenticated with check (true);
create policy "authenticated users can update expenses" on public.expenses for update to authenticated using (true) with check (true);
